title: "getoptlong.sh Documentation"
description: "Documentation and resources for getoptlong.sh"
theme: minima

plugins:
  - jekyll-feed

markdown: kramdown
highlighter: rouge

# Disable automatic page navigation
header_pages: []

# Exclude specific files from navigation
exclude:
  - qiita-article.md

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"