name: Run Bats Tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, ubuntu-22.04, macos-15, macos-14, macos-13 ]
    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Bats (Linux)
      if: runner.os == 'Linux'
      uses: tecolicom/actions-use-apt-tools@v1
      with:
        tools: bats

    - name: Set up Bats (macOS)
      if: runner.os == 'macOS'
      uses: tecolicom/actions-use-homebrew-tools@v1
      with:
        tools: make bash bats-core

    - name: Set up ENV (macOS)
      if: runner.os == 'macOS'
      run: |
        PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"
        sed 's/^ *//' << END >> $GITHUB_ENV
            PATH=$PATH
        END

    - name: run test
      run: |
        echo PATH="$PATH"
        which bash
        bash --version
        which gmake
        cd t
        gmake --version
        gmake test
