name: Run Bats Tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Bats (Linux)
      if: runner.os == 'Linux'
      uses: tecolicom/actions-use-apt-tools@v1
      with:
        tools: bats

    - name: Set up Bats (macOS)
      if: runner.os == 'macOS'
      uses: tecolicom/actions-use-homebrew-tools@v1
      with:
        tools: bats-core

    - run: make test
